global:
  scrape_interval: 15s
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alertmanager:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node_exporter
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: simple_server
    static_configs:
      - targets: ['server:8090']
  
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

remote_write:
  - url: "http://workers:9201/write"
